### ISSUE TITLE
Removes Special Characters.

### ISSUE THREAD

**Issue by bamne123** [blakeembrey/title-case#13] opened 2018-06-26 13:43 UTC
Hi,

When i use title-case with special characters in the text, it removes all the special characters and returns only the text.

Regards,
Nilesh

**Comment by blakeembrey** [comment] 2018-09-20 15:41
Closing as duplicate of #11. Happy to accept a PR rewriting the functionality.

**Closed by blakeembrey** 2018-09-20 15:41 UTC
